INSERT INTO role (id, name) VALUES (1, 'ADMIN') ON DUPLICATE KEY UPDATE name = 'ADMIN';
INSERT INTO role (id, name) VALUES (2, 'USER') ON DUPLICATE KEY UPDATE name = 'USER';
INSERT INTO criterion (id, name) VALUES (1, 'USER_NOTES') ON DUPLICATE KEY UPDATE name = 'USER_NOTES';